/**
 * Structural mirror of frontend/src/index.css.
 *
 * Two deliberate divergences from the web:
 *
 * 1. Tailwind v3 + NativeWind v4. The web is on Tailwind v4's CSS-first
 *    @theme, which NativeWind has no stable support for. Token NAMES are
 *    identical, so utility classes are copy-pasteable between the two.
 *
 * 2. Weights 550 and 650 do not exist as static Inter faces and variable fonts
 *    are unreliable on Android, so they collapse onto 600. The ramp is
 *    400 / 500 / 600 / 700 - see src/theme/typography.js.
 *
 * Colour values live in global.css, generated by scripts/sync-theme.js.
 */
const c = (name) => `rgb(var(--${name}) / <alpha-value>)`;

module.exports = {
  content: ["./app/**/*.{js,jsx}", "./src/**/*.{js,jsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: c("background"),
        foreground: c("foreground"),
        card: { DEFAULT: c("card"), foreground: c("card-foreground") },
        popover: { DEFAULT: c("popover"), foreground: c("popover-foreground") },
        primary: {
          DEFAULT: c("primary"),
          foreground: c("primary-foreground"),
          hover: c("primary-hover"),
          subtle: c("primary-subtle"),
          "subtle-foreground": c("primary-subtle-foreground"),
        },
        secondary: { DEFAULT: c("secondary"), foreground: c("secondary-foreground") },
        muted: { DEFAULT: c("muted"), foreground: c("muted-foreground") },
        accent: { DEFAULT: c("accent"), foreground: c("accent-foreground") },
        destructive: {
          DEFAULT: c("destructive"),
          foreground: c("destructive-foreground"),
          subtle: c("destructive-subtle"),
        },
        success: {
          DEFAULT: c("success"),
          foreground: c("success-foreground"),
          subtle: c("success-subtle"),
        },
        warning: {
          DEFAULT: c("warning"),
          foreground: c("warning-foreground"),
          subtle: c("warning-subtle"),
        },
        info: {
          DEFAULT: c("info"),
          foreground: c("info-foreground"),
          subtle: c("info-subtle"),
        },
        rating: c("rating"),
        scrim: {
          foreground: c("scrim-foreground"),
          "foreground-muted": c("scrim-foreground-muted"),
        },
        border: { DEFAULT: c("border"), strong: c("border-strong") },
        input: c("input"),
        ring: c("ring"),
        chart: {
          1: c("chart-1"),
          2: c("chart-2"),
          3: c("chart-3"),
          4: c("chart-4"),
          5: c("chart-5"),
        },
      },
      borderRadius: {
        xs: "8px",
        sm: "10px",
        md: "16px",
        lg: "20px",
        xl: "20px",
        "2xl": "20px",
        "3xl": "20px",
      },
      fontFamily: {
        sans: ["Inter_400Regular"],
        medium: ["Inter_500Medium"],
        semibold: ["Inter_600SemiBold"],
        bold: ["Inter_700Bold"],
      },
      fontSize: {
        display: ["32px", { lineHeight: "37px", letterSpacing: "-0.64px" }],
        h1: ["24px", { lineHeight: "30px", letterSpacing: "-0.36px" }],
        h2: ["19px", { lineHeight: "25px", letterSpacing: "-0.19px" }],
        h3: ["16px", { lineHeight: "22px", letterSpacing: "-0.08px" }],
        "body-lg": ["16px", { lineHeight: "25px" }],
        body: ["14px", { lineHeight: "22px" }],
        "body-sm": ["13px", { lineHeight: "20px" }],
        label: ["13px", { lineHeight: "17px" }],
        caption: ["12px", { lineHeight: "17px" }],
        price: ["15px", { lineHeight: "20px" }],
        "price-lg": ["20px", { lineHeight: "24px", letterSpacing: "-0.2px" }],
      },
    },
  },
  plugins: [],
};
