/**
 * Fast Casual Velocity, expressed as Tailwind utilities.
 *
 * The design language is deliberately its own: the native app is no longer a
 * port of the web's zinc theme. Colour values live in src/theme/palette.js and
 * reach this file as CSS variables through global.css, both generated by
 * scripts/sync-theme.js.
 *
 * Three things carry the look, and they are all here:
 *
 * 1. Neutral surfaces. `background` is a plain light grey, `card` is white.
 *    Most content sits directly on the canvas with no card behind it at all -
 *    a photograph with rounded corners and type underneath, the way a feed
 *    should read. Cards are for genuinely grouped content.
 *
 * 2. Soft, consistent curvature. Four radii do nearly all the work: `sm` (14)
 *    for thumbnails and small controls, `md` (18) for inputs and inset panels,
 *    `lg` (22) for cards and feed imagery, `3xl` (34) for sheet tops. Anything
 *    pressable is `rounded-full`.
 *
 * 3. Restrained type. Plus Jakarta Sans at 600/700 for headings, prices and
 *    labels; Inter for body copy. No 800 weight anywhere - display type earns
 *    its emphasis from size, not from mass.
 *
 * NativeWind v4 targets Tailwind 3, not the web's Tailwind 4 - that divergence
 * is why this file exists at all rather than a CSS-first @theme block.
 */
const c = (name) => `rgb(var(--${name}) / <alpha-value>)`;

module.exports = {
  content: ["./app/**/*.{js,jsx}", "./src/**/*.{js,jsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: c("background"),
        foreground: c("foreground"),
        card: { DEFAULT: c("card"), foreground: c("card-foreground") },
        popover: { DEFAULT: c("popover"), foreground: c("popover-foreground") },
        primary: {
          DEFAULT: c("primary"),
          foreground: c("primary-foreground"),
          hover: c("primary-hover"),
          bright: c("primary-bright"),
          subtle: c("primary-subtle"),
          "subtle-foreground": c("primary-subtle-foreground"),
        },
        tertiary: {
          DEFAULT: c("tertiary"),
          foreground: c("tertiary-foreground"),
          subtle: c("tertiary-subtle"),
          "subtle-foreground": c("tertiary-subtle-foreground"),
        },
        secondary: { DEFAULT: c("secondary"), foreground: c("secondary-foreground") },
        muted: { DEFAULT: c("muted"), foreground: c("muted-foreground") },
        accent: { DEFAULT: c("accent"), foreground: c("accent-foreground") },
        destructive: {
          DEFAULT: c("destructive"),
          foreground: c("destructive-foreground"),
          subtle: c("destructive-subtle"),
        },
        success: {
          DEFAULT: c("success"),
          foreground: c("success-foreground"),
          subtle: c("success-subtle"),
        },
        warning: {
          DEFAULT: c("warning"),
          foreground: c("warning-foreground"),
          subtle: c("warning-subtle"),
        },
        info: {
          DEFAULT: c("info"),
          foreground: c("info-foreground"),
          subtle: c("info-subtle"),
        },
        rating: c("rating"),
        scrim: {
          foreground: c("scrim-foreground"),
          "foreground-muted": c("scrim-foreground-muted"),
        },
        border: { DEFAULT: c("border"), strong: c("border-strong") },
        input: c("input"),
        ring: c("ring"),
        chart: {
          1: c("chart-1"),
          2: c("chart-2"),
          3: c("chart-3"),
          4: c("chart-4"),
          5: c("chart-5"),
        },
      },
      borderRadius: {
        xs: "10px",
        sm: "14px",
        md: "18px",
        lg: "22px",
        xl: "26px",
        "2xl": "30px",
        "3xl": "34px",
      },
      fontFamily: {
        // Inter: body copy. Weights 400/500/600/700.
        sans: ["Inter_400Regular"],
        medium: ["Inter_500Medium"],
        semibold: ["Inter_600SemiBold"],
        bold: ["Inter_700Bold"],
        // Plus Jakarta Sans: headings, labels, prices, CTAs.
        jakarta: ["PlusJakartaSans_600SemiBold"],
        "jakarta-bold": ["PlusJakartaSans_700Bold"],
      },
      fontSize: {
        // Plus Jakarta roles. Sized close to the iOS text styles, which are
        // tuned for a phone held at arm's length rather than for impact.
        display: ["30px", { lineHeight: "35px", letterSpacing: "-0.6px" }],
        h1: ["24px", { lineHeight: "29px", letterSpacing: "-0.5px" }],
        h2: ["19px", { lineHeight: "24px", letterSpacing: "-0.3px" }],
        h3: ["16px", { lineHeight: "21px", letterSpacing: "-0.2px" }],
        label: ["14px", { lineHeight: "18px", letterSpacing: "-0.05px" }],
        "label-sm": ["12px", { lineHeight: "16px" }],
        // A true eyebrow. Rare - most small text should just be small, not
        // shouted in capitals.
        overline: ["11px", { lineHeight: "14px", letterSpacing: "0.5px" }],

        // Inter roles - normal tracking, set for reading.
        "body-lg": ["16px", { lineHeight: "22px" }],
        body: ["15px", { lineHeight: "20px" }],
        "body-sm": ["13px", { lineHeight: "18px" }],
        caption: ["12px", { lineHeight: "16px" }],

        // Numerals. Tabular, so totals line up column to column.
        price: ["16px", { lineHeight: "20px", letterSpacing: "-0.2px" }],
        "price-lg": ["22px", { lineHeight: "26px", letterSpacing: "-0.5px" }],
        "price-xl": ["30px", { lineHeight: "34px", letterSpacing: "-0.8px" }],
      },
    },
  },
  plugins: [],
};
