export const FORM_FIELDS = {
  email: {
    name: "email",
    type: "email",
    placeholder: "Email",
    validation: "email",
  },
  password: {
    name: "password",
    type: "password",
    placeholder: "Password",
    validation: "password",
  },
  confirmPassword: {
    name: "confirmPassword",
    type: "password",
    placeholder: "Confirm Password",
    validation: "password",
  },
  name: {
    name: "name",
    type: "text",
    placeholder: "Full Name",
    validation: "name",
  },
  restaurantName: {
    name: "restaurantName",
    type: "text",
    placeholder: "Restaurant Name",
    validation: "restaurantName",
  },
  restaurantPhone: {
    name: "restaurantPhone",
    type: "tel",
    placeholder: "Phone Number",
    validation: "restaurantPhone",
  },
  restaurantAddress: {
    name: "restaurantAddress",
    type: "text",
    placeholder: "Restaurant Address",
    validation: "restaurantAddress",
  },
  restaurantCity: {
    name: "restaurantCity",
    type: "text",
    placeholder: "City",
    validation: "restaurantCity",
  },
  restaurantState: {
    name: "restaurantState",
    type: "text",
    placeholder: "State/Province",
    validation: "restaurantState",
  },
  restaurantZipCode: {
    name: "restaurantZipCode",
    type: "text",
    placeholder: "Zip Code",
    validation: "restaurantZipCode",
  },
  cuisineType: {
    name: "cuisineType",
    type: "text",
    placeholder: "Cuisine Type (e.g., Italian, Chinese)",
    validation: "cuisineType",
  },
  code: {
    name: "code",
    type: "text",
    placeholder: "000000",
    validation: "code",
    maxLength: 6,
  },
};

export const FORM_CONFIGS = {
  login: {
    fields: ["email", "password"],
    title: "Welcome Back!",
    description: "Log in to track your orders and save favorites.",
    submitText: "Log In",
    submitingText: "Logging in...",
  },
  register: {
    fields: ["name", "email", "password"],
    title: "Join Chow & Go",
    description: "Create an account to start ordering in seconds.",
    submitText: "Sign Up",
    submitingText: "Creating account...",
    hasRole: true,
    hasImage: true,
  },
  "restaurant-info": {
    fields: [
      "restaurantName",
      "restaurantPhone",
      "restaurantAddress",
      "restaurantCity",
      "restaurantState",
      "restaurantZipCode",
      "cuisineType",
    ],
    title: "Restaurant Information",
    description: "Tell us about your restaurant",
    submitText: "Complete Registration",
    submitingText: "Creating account...",
    showBackButton: true,
  },
  forgot: {
    fields: ["email"],
    title: "Reset Password",
    description: "Enter your email to get a verification code",
    submitText: "Send Code",
    submitingText: "Sending...",
    customForm: true,
  },
  otp: {
    fields: ["code"],
    title: "Reset Password",
    description: "Check your email for the 6-digit code",
    submitText: "Verify Code",
    submitingText: "Verifying...",
    customForm: true,
  },
  reset: {
    fields: ["password", "confirmPassword"],
    title: "Reset Password",
    description: "Choose a new password",
    submitText: "Set New Password",
    submitingText: "Resetting...",
    customForm: true,
  },
};
