/**
 * Generates global.css and src/theme/tokens.js from frontend/src/index.css.
 *
 * The web is Tailwind v4 (CSS-first @theme); NativeWind v4 targets Tailwind v3
 * and needs a config file, so the token *values* have to exist here too. Rather
 * than transcribe ~60 colours by hand in two places, derive them.
 *
 * Colours become space-separated RGB channels so Tailwind's <alpha-value> slot
 * resolves and `bg-primary/10` compiles. Shadows and type metrics have no CSS
 * equivalent in RN, so they land in tokens.js as JS values.
 *
 * Run after any change to the web palette:  npm run sync-theme
 */
const fs = require("fs");
const path = require("path");

const SOURCE = path.resolve(__dirname, "../../frontend/src/index.css");
const css = fs.readFileSync(SOURCE, "utf8");

// Web console chrome; meaningless on mobile.
const SKIP = /^--sidebar/;

function block(selector) {
  const start = css.indexOf(selector + " {");
  if (start === -1) throw new Error(`missing block: ${selector}`);
  const open = css.indexOf("{", start);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`unterminated block: ${selector}`);
}

function toChannels(value) {
  const hex = value.match(/^#([0-9a-f]{6})$/i);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
  }
  const rgb = value.match(/^rgb\(\s*(\d+)\s+(\d+)\s+(\d+)(?:\s*\/\s*([\d.]+))?\s*\)$/);
  if (rgb) return `${rgb[1]} ${rgb[2]} ${rgb[3]}`;
  return null;
}

function alphaOf(value) {
  const m = value.match(/\/\s*([\d.]+)\s*\)$/);
  return m ? Number(m[1]) : 1;
}

function parseColors(selector) {
  const out = {};
  for (const [, name, raw] of block(selector).matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    const value = raw.trim();
    if (SKIP.test(name) || name.startsWith("--elevation")) continue;
    const channels = toChannels(value);
    if (channels) out[name.slice(2)] = { channels, alpha: alphaOf(value) };
  }
  return out;
}

const light = parseColors(":root");
const dark = parseColors(".dark");

const missing = Object.keys(light).filter((k) => !(k in dark));
if (missing.length) throw new Error(`tokens missing a dark value: ${missing.join(", ")}`);

// ---------------------------------------------------------------- global.css
const varLines = (tokens) =>
  Object.entries(tokens)
    .map(([name, { channels }]) => `    --${name}: ${channels};`)
    .join("\n");

fs.writeFileSync(
  path.resolve(__dirname, "../global.css"),
  `@tailwind base;
@tailwind components;
@tailwind utilities;

/* GENERATED by scripts/sync-theme.js from frontend/src/index.css - do not edit.
   Channels are space-separated RGB so Tailwind's <alpha-value> resolves;
   bg-primary/10 does not compile against hex. */

@layer base {
  :root {
${varLines(light)}
  }

  .dark {
${varLines(dark)}
  }
}
`
);

// ------------------------------------------------------------- tokens.js
// Consumed by everything that takes a JS colour rather than a className:
// react-native-maps, @gorhom/bottom-sheet, StatusBar, charts, navigation theme.
const jsColors = (tokens) =>
  Object.entries(tokens)
    .map(([name, { channels, alpha }]) => {
      const [r, g, b] = channels.split(" ");
      const value = alpha === 1 ? `rgb(${r} ${g} ${b})` : `rgba(${r}, ${g}, ${b}, ${alpha})`;
      return `    ${JSON.stringify(name)}: "${value}",`;
    })
    .join("\n");

// Multi-layer CSS shadows collapse to RN's single shadow; these approximate the
// web's three elevation levels rather than reproducing them exactly.
const ELEVATION = `export const elevation = {
  subtle: {
    light: { shadowColor: "#09090b", shadowOpacity: 0.05, shadowRadius: 2, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
    dark: { shadowColor: "#000000", shadowOpacity: 0.5, shadowRadius: 2, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  },
  raised: {
    light: { shadowColor: "#09090b", shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
    dark: { shadowColor: "#000000", shadowOpacity: 0.6, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  },
  overlay: {
    light: { shadowColor: "#09090b", shadowOpacity: 0.2, shadowRadius: 25, shadowOffset: { width: 0, height: 12 }, elevation: 12 },
    dark: { shadowColor: "#000000", shadowOpacity: 0.7, shadowRadius: 25, shadowOffset: { width: 0, height: 12 }, elevation: 12 },
  },
};`;

fs.writeFileSync(
  path.resolve(__dirname, "../src/theme/tokens.js"),
  `// GENERATED by scripts/sync-theme.js from frontend/src/index.css - do not edit.
// For APIs that take a colour value rather than a className: the map SDK,
// bottom sheets, StatusBar, charts, the navigation theme.

export const colors = {
  light: {
${jsColors(light)}
  },
  dark: {
${jsColors(dark)}
  },
};

${ELEVATION}

export const radius = { xs: 8, sm: 10, md: 16, lg: 20, full: 9999 };

export const duration = { micro: 150, standard: 250, panel: 340, page: 300, image: 500 };

// cubic-bezier(0.22, 1, 0.36, 1) and cubic-bezier(0.4, 0, 1, 1)
export const easing = { standard: [0.22, 1, 0.36, 1], exit: [0.4, 0, 1, 1] };
`
);

// Guard: a token added to the web palette must also be mapped to a utility, or
// it silently never reaches a className.
const mapped = new Set();
const collect = (obj) => {
  for (const value of Object.values(obj)) {
    if (typeof value === "string") {
      const found = value.match(/var\(--([\w-]+)\)/);
      if (found) mapped.add(found[1]);
    } else {
      collect(value);
    }
  }
};
collect(require("../tailwind.config.js").theme.extend.colors);

const unmapped = Object.keys(light).filter((token) => !mapped.has(token));
if (unmapped.length) {
  console.error(`\n  tailwind.config.js does not map: ${unmapped.join(", ")}\n`);
  process.exit(1);
}

console.log(`synced ${Object.keys(light).length} colour tokens, all mapped`);
