/**
 * Generates global.css and src/theme/tokens.js from src/theme/palette.js.
 *
 * The palette is written once, in hex, and consumed two ways that need
 * different encodings:
 *
 *   global.css   space-separated RGB channels, so Tailwind's <alpha-value> slot
 *                resolves and `bg-primary/10` compiles. Hex does not.
 *   tokens.js    real colour strings, for the APIs that take a value rather
 *                than a className: MapLibre, bottom sheets, StatusBar, charts,
 *                the navigation theme.
 *
 * Shadows, radii and motion have no CSS-variable equivalent in RN, so they are
 * emitted straight into tokens.js.
 *
 * Run after any change to the palette:  npm run sync-theme
 */
const fs = require("fs");
const path = require("path");

// palette.js is ESM inside an app that Metro compiles, but this script runs in
// bare node. Read and evaluate the two exported objects rather than importing.
const paletteSource = fs.readFileSync(
  path.resolve(__dirname, "../src/theme/palette.js"),
  "utf8",
);

function parseExport(name) {
  const start = paletteSource.indexOf(`export const ${name} = {`);
  if (start === -1) throw new Error(`palette.js is missing an export named "${name}"`);
  const open = paletteSource.indexOf("{", start);
  let depth = 0;
  for (let i = open; i < paletteSource.length; i++) {
    if (paletteSource[i] === "{") depth++;
    else if (paletteSource[i] === "}" && --depth === 0) {
      // eslint-disable-next-line no-new-func
      return new Function(`return ${paletteSource.slice(open, i + 1)}`)();
    }
  }
  throw new Error(`unterminated object literal for "${name}"`);
}

function toChannels(value) {
  const hex = value.match(/^#([0-9a-f]{6})$/i);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
  }
  const rgb = value.match(/^rgb\(\s*(\d+)\s+(\d+)\s+(\d+)(?:\s*\/\s*([\d.]+))?\s*\)$/);
  if (rgb) return `${rgb[1]} ${rgb[2]} ${rgb[3]}`;
  throw new Error(`unsupported colour value: ${value}`);
}

function alphaOf(value) {
  const m = value.match(/\/\s*([\d.]+)\s*\)$/);
  return m ? Number(m[1]) : 1;
}

const normalize = (raw) =>
  Object.fromEntries(
    Object.entries(raw).map(([name, value]) => [
      name,
      { channels: toChannels(value), alpha: alphaOf(value) },
    ]),
  );

const light = normalize(parseExport("light"));
const dark = normalize(parseExport("dark"));

const missing = Object.keys(light).filter((k) => !(k in dark));
if (missing.length) throw new Error(`tokens missing a dark value: ${missing.join(", ")}`);

const extra = Object.keys(dark).filter((k) => !(k in light));
if (extra.length) throw new Error(`tokens missing a light value: ${extra.join(", ")}`);

// ---------------------------------------------------------------- global.css
const varLines = (tokens) =>
  Object.entries(tokens)
    .map(([name, { channels }]) => `    --${name}: ${channels};`)
    .join("\n");

fs.writeFileSync(
  path.resolve(__dirname, "../global.css"),
  `@tailwind base;
@tailwind components;
@tailwind utilities;

/* GENERATED by scripts/sync-theme.js from src/theme/palette.js - do not edit.

   Channels are space-separated RGB so Tailwind's <alpha-value> resolves;
   bg-primary/10 does not compile against hex.

   The dark block MUST be \`.dark:root\`, not \`.dark\`. react-native-css-interop
   only lifts variables into its theme when the selector is exactly \`:root\` or
   \`.dark:root\` (see css-to-rn/normalize-selectors.js). A plain \`.dark\` block
   parses fine, compiles fine, and is then dropped on the floor - every
   className-driven colour stays on its light value while anything reading
   tokens.js in JS flips, which looks like "dark mode half works". */

@layer base {
  :root {
${varLines(light)}
  }

  .dark:root {
${varLines(dark)}
  }
}
`,
);

// ------------------------------------------------------------------ tokens.js
const jsColors = (tokens) =>
  Object.entries(tokens)
    .map(([name, { channels, alpha }]) => {
      const [r, g, b] = channels.split(" ");
      const value = alpha === 1 ? `rgb(${r} ${g} ${b})` : `rgba(${r}, ${g}, ${b}, ${alpha})`;
      return `    ${JSON.stringify(name)}: "${value}",`;
    })
    .join("\n");

// RN collapses a multi-layer CSS shadow to one, so these approximate the
// design's elevation tiers rather than reproducing them.
//
// They are deliberately faint. A card that announces itself with a heavy drop
// shadow is the fastest way to make an interface look cheap; separation here
// comes from the gap between a white card and a grey canvas, with the shadow
// only softening the edge.
//
// `glow` is the exception: a green-tinted lift used only under a floating
// primary CTA, which is the one element that genuinely hovers over the page.
const ELEVATION = `export const elevation = {
  subtle: {
    light: { shadowColor: "#16161a", shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
    dark: { shadowColor: "#000000", shadowOpacity: 0.4, shadowRadius: 10, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  },
  raised: {
    light: { shadowColor: "#16161a", shadowOpacity: 0.07, shadowRadius: 18, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
    dark: { shadowColor: "#000000", shadowOpacity: 0.5, shadowRadius: 18, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
  },
  overlay: {
    light: { shadowColor: "#16161a", shadowOpacity: 0.16, shadowRadius: 32, shadowOffset: { width: 0, height: 14 }, elevation: 12 },
    dark: { shadowColor: "#000000", shadowOpacity: 0.65, shadowRadius: 32, shadowOffset: { width: 0, height: 14 }, elevation: 12 },
  },
  glow: {
    light: { shadowColor: "#00874f", shadowOpacity: 0.26, shadowRadius: 22, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
    dark: { shadowColor: "#00c46e", shadowOpacity: 0.24, shadowRadius: 22, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
  },
};`;

fs.writeFileSync(
  path.resolve(__dirname, "../src/theme/tokens.js"),
  `// GENERATED by scripts/sync-theme.js from src/theme/palette.js - do not edit.
// For APIs that take a colour value rather than a className: the map SDK,
// bottom sheets, StatusBar, charts, the navigation theme.

export const colors = {
  light: {
${jsColors(light)}
  },
  dark: {
${jsColors(dark)}
  },
};

${ELEVATION}

// Mirrors borderRadius in tailwind.config.js. Cards sit at \`lg\`, hero surfaces
// and sheets at \`xl\`, and anything pressable is \`full\`.
export const radius = { xs: 10, sm: 14, md: 18, lg: 22, xl: 26, "2xl": 30, "3xl": 34, full: 9999 };

export const duration = { micro: 150, standard: 250, panel: 340, page: 300, image: 500 };

// cubic-bezier(0.22, 1, 0.36, 1) and cubic-bezier(0.4, 0, 1, 1)
export const easing = { standard: [0.22, 1, 0.36, 1], exit: [0.4, 0, 1, 1] };
`,
);

// Guard: a token added to the palette must also be mapped to a utility, or it
// silently never reaches a className.
const mapped = new Set();
const collect = (obj) => {
  for (const value of Object.values(obj)) {
    if (typeof value === "string") {
      const found = value.match(/var\(--([\w-]+)\)/);
      if (found) mapped.add(found[1]);
    } else {
      collect(value);
    }
  }
};
collect(require("../tailwind.config.js").theme.extend.colors);

const unmapped = Object.keys(light).filter((token) => !mapped.has(token));
if (unmapped.length) {
  console.error(`\n  tailwind.config.js does not map: ${unmapped.join(", ")}\n`);
  process.exit(1);
}

console.log(`synced ${Object.keys(light).length} colour tokens, all mapped`);
